# Generated by Django 4.0 on 2022-02-04 22:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("catalog", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelTable(
            name="contacttype",
            table="contact_type",
        ),
        migrations.AlterModelTable(
            name="dataobjecttype",
            table="dataobject_type",
        ),
        migrations.AlterModelTable(
            name="datasourcecontact",
            table="datasource_contact",
        ),
        migrations.AlterModelTable(
            name="datasourcetype",
            table="datasource_type",
        ),
        migrations.AlterModelTable(
            name="datasourcetypeparams",
            table="datasource_type_params",
        ),
    ]
