# Generated by Django 4.0 on 2022-02-04 23:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("catalog", "0002_alter_contacttype_table_alter_dataobjecttype_table_and_more"),
    ]

    operations = [
        migrations.AlterModelTable(
            name="contacttype",
            table="catalog_contact_type",
        ),
        migrations.AlterModelTable(
            name="dataobjecttype",
            table="catalog_dataobject_type",
        ),
        migrations.AlterModelTable(
            name="datasourcecontact",
            table="catalog_datasource_contact",
        ),
        migrations.AlterModelTable(
            name="datasourcetype",
            table="catalog_datasource_type",
        ),
        migrations.AlterModelTable(
            name="datasourcetypeparams",
            table="catalog_datasource_type_params",
        ),
    ]
